export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {
      flexbox: 'no-2009',
      grid: 'autoplace',
    },
    cssnano: process.env.NODE_ENV === 'production' ? {
      preset: ['default', {
        discardComments: {
          removeAll: true,
        },
        normalizeWhitespace: true,
        minifySelectors: true,
        minifyParams: true,
        minifyFontValues: true,
        minifyGradients: true,
        minifyTimingFunctions: true,
        minifyTransforms: true,
        minifyBorderRadius: true,
        minifyCalc: true,
        minifyColor: true,
        minifyDisplayValues: true,
        minifyFontWeight: true,
        minifyGradients: true,
        minifyHex: true,
        minifyHwb: true,
        minifyIdents: true,
        minifyInitial: true,
        minifyKeyframes: true,
        minifyMediaQueries: true,
        minifyOutline: true,
        minifySelectors: true,
        minifyShorthands: true,
        minifySyntax: true,
        minifyTimingFunctions: true,
        minifyTransforms: true,
        minifyUrl: true,
        minifyZindex: true,
        normalizeCharset: true,
        normalizeDisplayValues: true,
        normalizePositions: true,
        normalizeRepeatStyle: true,
        normalizeString: true,
        normalizeTimingFunctions: true,
        normalizeUnicode: true,
        normalizeUrl: true,
        normalizeWhitespace: true,
        orderedValues: true,
        reduceIdents: true,
        reduceInitial: true,
        reduceTransforms: true,
        svgo: true,
        uniqueSelectors: true,
        zindex: true,
      }],
    } : false,
  },
}
